version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Decode secrets
          command: echo $SECRET_PROPERTIES | base64 --decode --ignore-garbage > secrets.properties

      - run:
          name: Decode Debug Google Services Json
          command: echo $SERVICES_JSON_DEBUG | base64 --decode --ignore-garbage > app/src/debug/google-services.json
      - run:
          name: Decode Prod Google Services Json
          command: echo $SERVICES_JSON_PROD | base64 --decode --ignore-garbage > app/src/release/google-services.json
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Run Unit Tests
          command: ./gradlew test
      - run:
          name: Run Linters
          command: ./gradlew check
      - run:
          name: Build
          command: ./gradlew assemble
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
